log:
  version: 1
  formatters:
    customFormatter:
      format: '[%(asctime)s]%(levelname)s - %(filename)s#%(funcName)s:%(lineno)d: %(message)s'
      datefmt: '%Y/%m/%d %H:%M:%S'
  loggers:
    app_logger:
      handlers: [fileRotatingHandler,consoleHandler]
      level: DEBUG
      qualname: file
      propagate: no
  handlers:
    fileRotatingHandler:
      formatter: customFormatter
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      filename: app.log
      encoding: utf8
      when: 'D'
      interval: 1
      backupCount: 14
    consoleHandler:
      class: logging.StreamHandler
      level: DEBUG
      formatter: customFormatter
      stream: ext://sys.stdout
  root:
    level: DEBUG
database:
  host: "localhost"
  dbname: "postgres"
  user: "postgres"
  password: "postgresk"
app:
  port: 5000
  sessionTimeoutMinutes: 30
  secretKey: user