log:
  level: 'DEBUG'
  file_name: './logs/app.log'
database:
  host: "localhost"
  dbname: "postgres"
  user: "postgres"
  password: "postgresk"
app:
  port: 5000
  sessionTimeoutMinutes: 30
  secretKey: user